### ISSUE TITLE
Install openjdk-8 on jenkins slaves

### ISSUE THREAD

**Issue by jacksgt** [vision-it/vision-jenkins#5]
Install `openjdk-8-jre-headless` on all jenkins slaves.

Without:
```
[03/07/18 16:05:15] [SSH] Opening SSH connection to vision02.iis.fhg.de:22.
[03/07/18 16:05:15] [SSH] WARNING: SSH Host Keys are not being verified. Man-in-the-middle attacks may be possible against this connection.
[03/07/18 16:05:15] [SSH] Authentication successful.
[03/07/18 16:05:16] [SSH] The remote user's environment is:
HOME='/home/jenkins'
IFS=' 	
'
LOGNAME='jenkins'
MAIL='/var/mail/jenkins'
OPTIND='1'
PATH='/usr/local/bin:/usr/bin:/bin:/usr/games'
PPID='15143'
PS1='$ '
PS2='> '
PS4='+ '
PWD='/home/jenkins'
SHELL='/bin/sh'
SSH_CLIENT='10.55.63.23 60870 22'
SSH_CONNECTION='10.55.63.23 60870 10.55.63.152 22'
USER='jenkins'
[03/07/18 16:05:16] [SSH] Checking java version of java
Couldn't figure out the Java version of java
sh: 1: java: not found

[03/07/18 16:05:16] [SSH] Checking java version of /usr/bin/java
Couldn't figure out the Java version of /usr/bin/java
sh: 1: /usr/bin/java: not found

[03/07/18 16:05:16] [SSH] Checking java version of /usr/java/default/bin/java
Couldn't figure out the Java version of /usr/java/default/bin/java
sh: 1: /usr/java/default/bin/java: not found

[03/07/18 16:05:16] [SSH] Checking java version of /usr/java/latest/bin/java
Couldn't figure out the Java version of /usr/java/latest/bin/java
sh: 1: /usr/java/latest/bin/java: not found

[03/07/18 16:05:16] [SSH] Checking java version of /usr/local/bin/java
Couldn't figure out the Java version of /usr/local/bin/java
sh: 1: /usr/local/bin/java: not found

[03/07/18 16:05:16] [SSH] Checking java version of /usr/local/java/bin/java
Couldn't figure out the Java version of /usr/local/java/bin/java
sh: 1: /usr/local/java/bin/java: not found

[03/07/18 16:05:16] [SSH] Checking java version of /home/jenkins/jdk/bin/java
Couldn't figure out the Java version of /home/jenkins/jdk/bin/java
sh: 1: /home/jenkins/jdk/bin/java: not found

Linux vision02 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
Installing JDK jdk-8u144-oth-JPR
Downloading JDK from http://download.oracle.com/otn/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz
Oracle now requires Oracle account to download previous versions of JDK. Please specify your Oracle account username/password.
java.io.IOException: Could not find any known supported java version (a minimum level of 8 is required) in [java, /usr/bin/java, /usr/java/default/bin/java, /usr/java/latest/bin/java, /usr/local/bin/java, /usr/local/java/bin/java, /home/jenkins/jdk/bin/java], and we also failed to install JDK as a fallback
	at hudson.plugins.sshslaves.SSHLauncher.resolveJava(SSHLauncher.java:954)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:836)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:820)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.AbortException: Unable to install JDK unless a valid Oracle account username/password is provided in the system configuration.
	at hudson.tools.JDKInstaller.locate(JDKInstaller.java:524)
	at hudson.plugins.sshslaves.SSHLauncher.attemptToInstallJDK(SSHLauncher.java:1075)
	at hudson.plugins.sshslaves.SSHLauncher.resolveJava(SSHLauncher.java:951)
	... 6 more
[03/07/18 16:05:20] Launch failed - cleaning up connection
[03/07/18 16:05:20] [SSH] Connection closed.
```

With openjdk-9-jre-headless:
```
[03/07/18 16:09:58] [SSH] Opening SSH connection to vision02.iis.fhg.de:22.
[03/07/18 16:09:58] [SSH] WARNING: SSH Host Keys are not being verified. Man-in-the-middle attacks may be possible against this connection.
[03/07/18 16:09:58] [SSH] Authentication successful.
[03/07/18 16:09:58] [SSH] The remote user's environment is:
HOME='/home/jenkins'
IFS=' 	
'
LOGNAME='jenkins'
MAIL='/var/mail/jenkins'
OPTIND='1'
PATH='/usr/local/bin:/usr/bin:/bin:/usr/games'
PPID='18189'
PS1='$ '
PS2='> '
PS4='+ '
PWD='/home/jenkins'
SHELL='/bin/sh'
SSH_CLIENT='10.55.63.23 60892 22'
SSH_CONNECTION='10.55.63.23 60892 10.55.63.152 22'
USER='jenkins'
[03/07/18 16:09:58] [SSH] Checking java version of java

[03/07/18 16:09:59] [SSH] java -version returned 9-debian.
[03/07/18 16:09:59] [SSH] Starting sftp client.
[03/07/18 16:09:59] [SSH] Copying latest slave.jar...
[03/07/18 16:09:59] [SSH] Copied 745,674 bytes.
Expanded the channel window size to 4MB
[03/07/18 16:09:59] [SSH] Starting slave process: cd "/home/jenkins" && java  -jar slave.jar

<===[JENKINS REMOTING CAPACITY]===>ERROR: Unexpected error in launching a slave. This is probably a bug in Jenkins.
java.lang.IllegalStateException: Already connected
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:514)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:413)
	at hudson.plugins.sshslaves.SSHLauncher.startSlave(SSHLauncher.java:1110)
	at hudson.plugins.sshslaves.SSHLauncher.access$500(SSHLauncher.java:148)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:845)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:820)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[03/07/18 16:10:02] Launch failed - cleaning up connection
[03/07/18 16:10:02] [SSH] Connection closed.
```

=> `openjdk-8-jre-headless` works

**Comment by martialblog** [comment]
My solution would be: Create a manifest that only installs JDK and include it in the build_slave role
